### ISSUE TITLE
Can not open chat anymore in latest android

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-android#44]
If I try to connect to another  instance of nunchuk on Android or on desktop,  the chat does not open anymore in latest version. 
Instead I get an empty yellow error message,  see screenshot ...
So I can't sign collaborative wallets or can't make them anymore. 
Tried on 2 different android devices,  same bug.
Tried one Linux and one windows machine,  chat only synced with desktop Pc not android. 
![Screenshot_20240104_121905_Nunchuk](https://github.com/nunchuk-io/nunchuk-android/assets/105175715/c2ed6734-fba9-4007-8a7d-1a9ba2e3132e)

**Comment by Funman2** [comment]
Hey, checked a little further and chat works flawlessly on version 1.9.37, only in latest 1.9.38 it does not work.

**Comment by JayceLuong** [comment]
Thank you for reporting it. We have fixed it, and it will apply to the next release.

**Comment by Funman2** [comment]
Great, it chat and collab signing works perfectly now in combination of android and desktop app! Fixed. Thanks.
Still cancel a TX does not go through in messenger when cancelled on android, only when canceled on desktop, the signed TX will go away , so basically a cancel never synncs? Is that intended behavoir?

**Comment by Funman2** [comment]
Great, chat and collab signing works perfectly now in combination of android and desktop app with latest playstore version 1.9.39 ( the version is still missing on github though...) Fixed. Thanks!

Still cancel a TX does not go through in messenger when cancelled on android, only when canceled on desktop, the signed TX will go away , so basically a cancel never synncs? Is that intended behavior?
